name: car
description: car project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  fixnum: ^1.0.1
  flutter_screenutil: ^5.8.2
  shared_preferences: ^2.0.17
  flutter_easyloading: ^3.0.5
  crypto: ^3.0.2
  dio_cookie_manager: ^3.0.0
  cached_network_image: ^3.2.3
  fluttertoast: ^8.1.2
  permission_handler: ^10.2.0
  protobuf: ^2.1.0
  sign_in_with_apple: ^4.1.0
  jverify: ^2.2.9
  card_swiper: ^2.0.4
  webview_flutter: ^4.0.6
  url_launcher: ^6.1.10
  photo_view: ^0.14.0
  image_picker: ^0.8.6+1
  flutter_bugly_latest: ^1.0.1
  logger: ^1.3.0
  fluwx: ^4.2.4+1
  connectivity_plus: ^4.0.1
  screenshot: ^1.3.0
  flutter_floating: ^1.0.5
  zego_express_engine: ^3.3.1
  svgaplayer_flutter: ^2.2.0
  fl_umeng: ^3.5.0
  device_info_plus: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true